/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx,mdx}',
    './components/**/*.{js,jsx,ts,tsx,mdx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#ff9997',
        'on-primary-fixed': '#3c0700',
        secondary: '#ffb3b1',
        'outline-variant': '#5b403f',
        'on-secondary': '#620e16',
        'tertiary-fixed-dim': '#6fd8cc',
        'on-primary': '#611200',
        'on-tertiary-container': '#00302c',
        'surface-container-highest': '#353534',
        'tertiary-fixed': '#8cf4e8',
        outline: '#ab8987',
        'primary-fixed': '#ffdad2',
        'inverse-surface': '#e5e2e1',
        'inverse-primary': '#b42900',
        'on-primary-container': '#550e00',
        'on-primary-fixed-variant': '#891d00',
        'secondary-fixed': '#ffdad8',
        'on-error': '#690005',
        'on-secondary-fixed': '#410007',
        background: '#131313',
        'on-surface-variant': '#e4bebc',
        'surface-container-low': '#1c1b1b',
        primary: '#ffb4a2',
        'secondary-fixed-dim': '#ffb3b1',
        'surface-container-high': '#2a2a2a',
        'surface-tint': '#ffb4a2',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#00504a',
        'surface-variant': '#353534',
        'surface-bright': '#393939',
        'on-secondary-fixed-variant': '#81262a',
        'on-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'primary-fixed-dim': '#ffb4a2',
        'on-tertiary-fixed': '#00201d',
        surface: '#131313',
        'inverse-on-surface': '#313030',
        'on-error-container': '#ffdad6',
        'secondary-container': '#81262a',
        tertiary: '#6fd8cc',
        'surface-container': '#201f1f',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary': '#003733',
        'surface-dim': '#131313',
        'primary-container': '#ff562b',
        error: '#ffb4ab',
        'tertiary-container': '#2fa096',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
};

export default config;
